def get_flag_emoji(country):
    flag_emojis = {
        "Andorra": "🇦🇩",
        "United Arab Emirates": "🇦🇪",
        "Albania": "🇦🇱",
        "Armenia": "🇦🇲",
        "Argentina": "🇦🇷",
        "Austria": "🇦🇹",
        "Australia": "🇦🇺",
        "Azerbaijan": "🇦🇿",
        "Bosnia": "🇧🇦",
        "Bangladesh": "🇧🇩",
        "Belgium": "🇧🇪",
        "Bulgaria": "🇧🇬",
        "Bolivia": "🇧🇴",
        "Brazil": "🇧🇷",
        "Belarus": "🇧🇾",
        "Canada": "🇨🇦",
        "Switzerland": "🇨🇭",
        "Chile": "🇨🇱",
        "China": "🇨🇳",
        "Colombia": "🇨🇴",
        "Costa Rica": "🇨🇷",
        "Cuba": "🇨🇺",
        "Cyprus": "🇨🇾",
        "Czechia": "🇨🇿",
        "Germany": "🇩🇪",
        "Denmark": "🇩🇰",
        "Ecuador": "🇪🇨",
        "Estonia": "🇪🇪",
        "Egypt": "🇪🇬",
        "Spain": "🇪🇸",
        "European Union": "🇪🇺",
        "Finland": "🇫🇮",
        "France": "🇫🇷",
        "United Kingdom": "🇬🇧",
        "Georgia": "🇬🇪",
        "Greece": "🇬🇷",
        "Guatemala": "🇬🇹",
        "Hong Kong SAR China": "🇭🇰",
        "Croatia": "🇭🇷",
        "Hungary": "🇭🇺",
        "Ireland": "🇮🇪",
        "Israel": "🇮🇱",
        "India": "🇮🇳",
        "Iraq": "🇮🇶",
        "Iran": "🇮🇷",
        "Iceland": "🇮🇸",
        "Italy": "🇮🇹",
        "Japan": "🇯🇵",
        "South Korea": "🇰🇷",
        "Lebanon": "🇱🇧",
        "Lithuania": "🇱🇹",
        "Luxembourg": "🇱🇺",
        "Latvia": "🇱🇻",
        "Morocco": "🇲🇦",
        "Monaco": "🇲🇨",
        "Moldova": "🇲🇩",
        "Montenegro": "🇲🇪",
        "Macao Sar China": "🇲🇴",
        "Malta": "🇲🇹",
        "Mexico": "🇲🇽",
        "Malaysia": "🇲🇾",
        "Netherlands": "🇳🇱",
        "Norway": "🇳🇴",
        "Nepal": "🇳🇵",
        "New Zealand": "🇳🇿",
        "Oman": "🇴🇲",
        "Panama": "🇵🇦",
        "Peru": "🇵🇪",
        "Philippines": "🇵🇭",
        "Pakistan": "🇵🇰",
        "Poland": "🇵🇱",
        "Puerto Rico": "🇵🇷",
        "Palestinian Territories": "🇵🇸",
        "Portugal": "🇵🇹",
        "Paraguay": "🇵🇾",
        "Qatar": "🇶🇦",
        "Romania": "🇷🇴",
        "Serbia": "🇷🇸",
        "Russia": "🇷🇺",
        "Saudi Arabia": "🇸🇦",
        "Sweden": "🇸🇪",
        "Slovenia": "🇸🇮",
        "Slovakia": "🇸🇰",
        "Sierra Leone": "🇸🇱",
        "San Marino": "🇸🇲",
        "Senegal": "🇸🇳",
        "Thailand": "🇹🇭",
        "Turkey": "🇹🇷",
        "Taiwan": "🇹🇼",
        "Ukraine": "🇺🇦",
        "United Nations": "🇺🇳",
        "United States": "🇺🇸",
        "Uruguay": "🇺🇾",
        "Uzbekistan": "🇺🇿",
        "Vatican City": "🇻🇦",
        "Venezuela": "🇻🇪",
        "Vietnam": "🇻🇳",
        "Kosovo": "🇽🇰",
        "Yemen": "🇾🇪",
        "South Africa": "🇿🇦"
    }
    return flag_emojis.get(country,country)
